spring:
  application:
    name: Iron Gate
  
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expiration: ${JWT_EXPIRATION:86400000} # 24 horas en millisegundos
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 días en millisegundos
