name: Trigger auto deployment for iron-gate

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/iron-gate-AutoDeployTrigger-1069d6fd-fb5c-445e-a4fd-6ef561197bdf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IRONGATE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IRONGATE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IRONGATE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.IRONGATE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IRONGATE_REGISTRY_PASSWORD }}
          containerAppName: iron-gate
          resourceGroup: IronGate
          imageToBuild: ghcr.io/iron-gate:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


